### ISSUE TITLE
Users API: When show only to friends mode is active, still visible to everyone

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#7916] opened 2016-05-17 20:19 UTC
Had a newbie unfortunately arrive at my location by simply clicking on my name.
Sorta startled me, as I was testing the Pull requests working :P 

https://metaverse.highfidelity.com/api/v1/users?status=online shows status and location even if one is marked as show friends only.

**Comment by birarda** [comment] 2016-05-20 00:57
Hey @Menithal - this should be not be the case. Let's look into it. Reach out to me (Slack since I see you there) so we can do a live test while you're online and marked for friends only.

**Comment by Menithal** [comment] 2016-05-20 08:07
@birarda sure. I'll be around during your guys morning.

Although, this can be easilly replicated by running the default users.js script, setting it to friends only and then opening [status window ](https://metaverse.highfidelity.com/api/v1/users?status=online) in incognito and looking for your name and location through there..

**Comment by birarda** [comment] 2016-05-21 00:08
I've got a fix for this pending on the server side of things. Should be out this evening. I'll close this once it's deployed and confirmed working.

**Closed** 2016-05-21 00:35 UTC
