### ISSUE TITLE
MyAvatar.addThrust({x:0,y:#,z:0}) Will not work if user is walking on entity.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#7842] opened 2016-05-08 12:20 UTC
MyAvatar.addThrust({x:0,y:+#,z:0}) doesnt seem to apply when user is simply walking. This is regardless if the thrust is within a update thread.
Once user flies, does the thrust get applied.

To reproduce, simply open console, and paste in the following while standing on entity. and then when flying:

> MyAvatar.addThrust({x:0,y:9001,z:0}) 

Expected should be pushing up, like it does when flying. Nothing happens when on an entity. Mean while

> MyAvatar.addThrust({x:0,y:0,z:9001})

Moves you in the z direction in both cases.
 
This issue is demonstrated at the start of this video: 
https://www.youtube.com/watch?v=5KCFhcqIe-k

In the video, I target two entities, and it gets an average of the two, and adds a thrust the average. However the Y does not kick in, until I am off the platform and "flying"

Infact I think the gravity should be adjusted to something of a constant, similar to entities on Avatars, and not the magnetic attraction to entities we have now.

This issue blocks https://worklist.net/20824 in terms of scripting, but Ill continue working on the models, textures and sound

**Comment by Menithal** [comment] 2016-05-13 16:41
Currently being worked on in #7874

**Comment by hyperlogic** [comment] 2016-05-25 18:40
#7974 has been merged into master.  Re-open this ticket if the issue is still occurring.

**Closed by hyperlogic** 2016-05-25 18:40 UTC
