### ISSUE TITLE
MyAvatar.addThrust Inconsitancies and Incorrect ground values

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#9185] opened 2016-12-11 11:08 UTC
It has feeled like addThrust adds more than what is specified for the Y, when the user is attached to a ground causing the user to go up more than to the direction the thrust should be going in.

So I decided to investigate, and now I have a test case for this and replication

In an empty domain:
Using the being of light avatar

```
MyAvatar.skeletonURL = "";
MyAvatar.scale= 1;
MyAvatar.position = Vec3.ZERO;
MyAvatar.velocity = Vec3.ZERO;
MyAvatar.orientation = Quat.ZERO;
MyAvatar.addThrust({x:0, y:5000, z:5000});
```
Avatar gets relocated to a position where the y and the z axis are equal.

Doing this multiple times can result in to different values!
Expected would be a consistant value, but it wasnt.
 I got either 11.1, 22.2 or 33.3, but atleast both values were equal.

Now when we add a platform in the near the center, with the avatar still located as close as possible to 0,0,0 when placed ontop

```
MyAvatar.skeletonURL = "";
Entities.addEntity({type:"Box", dimensions:{x:10,y:0.5,z:10}, position:{x:0,y:-1.3062, z:0}, lifetime: 10});
MyAvatar.scale= 1;
MyAvatar.velocity = Vec3.ZERO;
MyAvatar.position = Vec3.ZERO;
MyAvatar.orientation = Quat.ZERO;
Script.setTimeout(function () {
MyAvatar.addThrust({x:0, y:5000, z:5000});
},1000);
```
The avatar gets pushed to a much, much! more higher altitude than of z axis.

I got values range from {0, 13.5, 11.1} to {0, 27.2, 22.2} , but in all cases, the y axis was always larger, unlike if the user was flying.

Setting the thrust value to 50k causes some -wild- fluctuations, in which the avatar can get catapulted half a kilometer off in altitude compared to the Z axis.

The test cases use large values to demonstrate the issue that rises when multiple small thrusts are applied, and how it will effect the accuracy of such. 

The above inconsistency effects our ability to create alternative methods of locomotion within High Fidelity. Such as the hookgun script, or an alternative climby like locamotion.

**Comment by AndrewMeadows** [comment] 2017-06-20 21:34
Here is text I added to the corresponding internal fogbugz case 2550:


`MyAvatar.addThrust()` is a bad idea.  It shouldn't be used, but we keep it around because:

(1) As legacy support for scripts that already use it.

(2) Philip likes to use it when he's experimenting with script-driven avatar motion.

 
Why is `MyAvatar.addThrust()` bad?  Several reasons:

(a) Its units are not obvious.  Do you know the units of thrust?  It just so happens, as a fluke of how "thrust" was implemented, the units are "meters per second squared".  It is an acceleration...

(b) ... but only for a limited time.  The change in velocity depends on how long the acceleration is applied: the "deltaTime".  The formula is as follows:

    `deltaVelocity = acceleration * deltaTime`

But how long is "deltaTime"?  It is the period of one main-loop frame.  Thrust is applied for "deltaTime = 1/fps" (where fps = frames per second") and then it is cleared to zero and the thrust must be re-applied with a fresh `addThrust()` call.  Since the frame rate of the interface is variable the effect of thrust on an object must also be variable.  It might pick up a lot of speed when the FPS is low, or it might pick up only a little bit when the FPS is high.

(c) So the script must constantly call `addThrust()` as fast as it can, but the script doesn't necessarily get to run every frame.   It might run every other frame, especially if the interface client is running a lot of scripts.  In short, the scripting environment (how many and what scripts are running) will influence the effects of `addThrust()`!


If we weren't using `addThrust()` to move the avatar around... what would we do instead?  Wouldn't it be nice if we could just set the avatar's velocity?  Even better, wouldn't it be nice if we could set its target velocity and give it a timescale to achieve that velocity?

BTW, that is basically how the keyboard control system works.  You press the W key to go forward and some code tells the avatar that it has a forward target velocity of some magnitude.  The avatar will speed up and achieve the target velocity over some period timescale.  If the timescale is short the avatar will quickly get up to speed, but if it is long the avatar will slowly ramp up to the final target speed.


Did you know there is a second target velocity motor that can be set via script?  It is true:

    `MyAvatar.motorVelocity`

    `MyAvatar.motorTimescale`

That feature is enabled by default.  At the moment it can be disabled/enabled via the menu:

    `Menu.setIsOptionChecked("Enable Scripted Motor Control", false);
`
Oh yeah, the frame in which the velocity is applied can be set to be "world", "local", and "camera".  It defaults to "local".

    `Menu.motorReferenceFrame = "camera";`

And "forward" is along negative Z-axis (I think).


BTW, did you know that you can disable the normal keyboard-controlled motor?  It is true:

    `Menu.setIsOptionChecked("Enable Default Motor Control", false);`

**Comment by AndrewMeadows** [comment] 2017-06-20 21:50
As to why the Z and Y components of motion would be affected differently...

My first theory would be that the avatar's "default motor" (the one that moves the avatar in response to pressing the `awsd` keys) is in effect and has anisotropic influence when the avatar is "on the ground".  The "default motor" is enabled not just when the `awsd` keys are mashed but also when the avatar is "braking"... that is, when the avatar is moving but the keys have been released.  The braking is eventually cleared to zero... but only after the avatar comes to a nearly complete stop.

But when the avatar is standing on the ground the braking doesn't have any effect on the vertical component of the avatar's velocity.  This is to allow the avatar to "fall" when it moves off a step but stops pressing the `awsd` keys.  The logic that decides when to enable disable the "braking" uses the avatar's velocity when deciding when to apply/remove the brakes.

To test this theory: try the addThrust() from a hover state, or wait until the avatar is completely at rest when standing on the ground.  Alternatively you can disable the "default motor" using some of the JS example code above and then see if the YZ motion is still non-equal.


Maybe what you should be doing when you want to launch the avatar:

(1) Disable "default motor"
(2) Set the velocity of the avatar so that it follows a ballistic trajectory (this is more reliable than using `addThrust()`)
(3) When you're done throwing the avatar around re-enable the "default motor"

**Comment by AndrewMeadows** [comment] 2017-06-20 22:01
The reason you get discrete values (like 11.1, 22.2 or 33.3) is because the thrust is applied for the duration of the frame.  The frame is typically multiples of the physics simulation "substep" period, which is 1/90th of a second (Note: 1/90 = 0.011).

The Bullet physics simulation is configured to only take fixed "substeps" (of 1/90th of a second), no matter the size of the "step".  The reason this is done is to help maintain simuation stability irregardless of the frame rate of the interface client.  What it means is that if we ask the physics simulation to step forward 1/80th of a second it will actually step forward 1/90th and save the remainder for later.  The next 1/80th of a second step will add the remainder and then take as many 1/90 second substeps as fit within the accumulated value.  Similarly, if we interface client framerate were to drop to only 15, then for each 1/15th of a second step the physics simulation will take six substeps of 1/90 seconds and will save any remainder for the next step.

**Comment by Menithal** [comment] 2017-06-21 03:41
Heya thanks for explaining that. Would have been good if the interface would be marked as such as it's really hard to dig up information on what method to use without documentation.

I'll give it a velocity a shot without motor control but I do remember trying it earlier before using addThrust and having issues, and addThrust just worked, to a degree...

This still however doesn't seem to explain why when standing on a platform do the values shift so much between y and the other axises.

**Comment by Menithal** [comment] 2017-06-21 03:43
Oh I just saw the second post. Thanks for the details! I'll give motor control and velocity a shot, and then if that works better, close this ticket.

**Comment by AndrewMeadows** [comment] 2017-06-21 15:18
Closing this case.  `MyAvatar.addThrust()` is working as intended, but I don't recommend using it.

A final note: Maybe we should change `MyAvatar.addThrust()` to use units of velocity (e.g. not be dependent on the frame timestep).  This would make its behavior more predictable and would be easier than the current way to add a delta velocity to MyAvatar's current velocity.  However, this would change the strenght of the method and any scripts currently using it would have to re-tune the values they submit.  Perhaps a better way forward would be to implement `MyAvatar.addVelocity()` and remove `MyAvatar.addThrust()`.

**Closed by AndrewMeadows** 2017-06-21 15:18 UTC

**Comment by Menithal** [comment] 2017-06-21 15:38
I agree on addVelocity and phasing out addThrust.

**Comment by Menithal** [comment] 2017-06-21 17:44
For anyone bumping into this ticket in the future, @AndrewMeadows  meant

`MyAvatar.motorReferenceFrame` with possible values `camera|avatar|world` :)
