### ISSUE TITLE
Model entities aren't auto resized if added further than around 12m away from camera

### ISSUE THREAD

**Issue by ctrlaltdavid** [highfidelity/hifi#7848] opened 2016-05-09 10:25 UTC
Repro: Use the attached script to add an FBX model at different distances from the camera position. At distances up to around 12m the model is auto-resized to its natural dimensions (and a program log message from Interface says "[DEBUG] Autoresizing: <model name>". At distances around 13m or greater the model is not resized (no program log entry) and the model ends up with dimensions of only 0.1m cube (i.e., essentially invisible).
[autoResize.zip](https://github.com/highfidelity/hifi/files/254754/autoResize.zip)

Very unexpectedly, if you then move close enough to them they are auto-resized.

If you don't move closer to them, then unexpectedly doing a "Reset Dimensions" in the entities editor the model's dimensions are reset to a 1.0m cube, not their correct natural dimensions.

**Comment by AndrewMeadows** [comment] 2016-11-02 23:05
I'll take this bug -- it is real and fundamental.  The problem is that the RenderableModelEntityItem::_model is not getting "loaded" (whatever that means) until... something triggers it.

**Comment by ZappoMan** [comment] 2016-11-02 23:15
@AndrewMeadows - I suspect this is by design... "auto resize" is only designed to work for when people are importing models using the edit tools where they are obviously looking at the model... if you use a script to create an entity that is out of view then it's not going to get resized until it's in view... script authors need to explicitly include the dimensions of their models if they're going to create them at a distance or potentially out of view.

**Comment by AndrewMeadows** [comment] 2016-11-03 17:28
This is fixed in PR-8992:  https://github.com/highfidelity/hifi/pull/8992

**Comment by AndrewMeadows** [comment] 2016-11-03 21:29
This is fixed.

**Closed by AndrewMeadows** 2016-11-03 21:29 UTC
Labels: Reviewed
