### ISSUE TITLE
Imediate crash caused by plugin load order.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [highfidelity/hifi#8963] opened 2016-10-31 01:03 UTC
On Beta 24 (and has happened before I couldn't initally log into Interface without it imediately crashing.
It' seems to be related to a timing issue during plugin loading. I moved hifiNeuron.dll, hifiSixense.dll, and oculus.dll out of the plugin folder and then login succeeded without a crash.   Then I moved the plugins back and this time it succeeded as well. (Perhaps this changed the order the plugins are loaded.)  it would be good if we had a way to detect what hardware is available and only load the plugins that are needed

Windows 10 Pro
i5-4570 @3.2GHz
12Gb Ram
Nvidia GTX 1070
HTC Vive

**Comment by hyperlogic** [comment] 2016-11-01 17:40
I could not reproduce this issue, however. If you are using a Vive, it could have been fixed by #8928.  Which landed in the most recent Beta relesase 5629 available [here](https://highfidelity.com/download/)

I've also submitted a PR that makes plugin load order deterministic.  This will help us reproduce plugin load race conditions, if they exist, during development/testing.

**Comment by hyperlogic** [comment] 2016-11-01 17:41
Please re-open if you see this problem again.

**Closed by hyperlogic** 2016-11-01 17:41 UTC
