### ISSUE TITLE
If you Stop Default scripts you can not bring up Edit>Running scripts.

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9916] opened 2017-03-16 00:19 UTC
Open Tablet. Go to Menu>Edit>Running scripts. Stop all scripts. The tablet will close (this is OK).

Now try and go to Edit>Running scripts from the menu. It will not work.

**Comment by vladest** [comment] 2017-03-18 15:02
starting on this

**Comment by vladest** [comment] 2017-03-19 08:40
Please, let me know what is expected behavior in Tablet Mode after stopping all scripts? Edit->Running scripts will not work since its expected to open tablet interface which is stopped now

**Comment by vladest** [comment] 2017-03-20 19:50
PR: https://github.com/highfidelity/hifi/pull/9954

**Comment by SamGondelman** [comment] 2018-11-06 22:42
resolved by 9954

**Closed by SamGondelman** 2018-11-06 22:42 UTC
